/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
   const group = useRef()
   const { nodes, materials, animations } = useGLTF('/johnny.glb')
   const { actions } = useAnimations(animations, group)
   useEffect(() => {
      actions.dance.play()
   })
   return (
      <group ref={group} {...props} dispose={null}>
         <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
            <primitive object={nodes.mixamorigHips} />
            <skinnedMesh
               geometry={nodes.Mesh.geometry}
               material={materials.Ch42_Body}
               skeleton={nodes.Mesh.skeleton}
               castShadow
            />
            <skinnedMesh
               geometry={nodes.Mesh_1.geometry}
               material={materials.Ch42_Hair}
               skeleton={nodes.Mesh_1.skeleton}
            />
         </group>
      </group>
   )
}

useGLTF.preload('/jhonny.glb')
